### ISSUE TITLE
Error "WARNING - SORRY - Does not support non-DEFAULT coordinates: 'PDGM_EPIC_LOCAL'"

### ISSUE THREAD

**Issue by KoalaGeo** [AuScope/geomodel-2-3dweb#2]
Error I'm getting in shell below: 

```shell
edd@edd-VirtualBox:~/Documents/gitkraken/geomodel-2-3dweb/scripts$ ./gocad2collada.py -g ~/Documents/UKGEOS/Horizons/01_Topography_50m_GGERFS_Predrill.ts config.json

2020-02-11 10:57:12,985 -- __main__ -- INFO - 
Processing /home/edd/Documents/UKGEOS/Horizons/01_Topography_50m_GGERFS_Predrill.ts
2020-02-11 10:57:13,030 -- lib.imports.gocad.gocad_importer -- WARNING - SORRY - Does not support non-DEFAULT coordinates: 'PDGM_EPIC_LOCAL'
2020-02-11 10:57:13,030 -- __main__ -- WARNING - WARNING - could not process /home/edd/Documents/UKGEOS/Horizons/01_Topography_50m_GGERFS_Predrill.ts
Traceback (most recent call last):
  File "./gocad2collada.py", line 513, in <module>
    converter.process(GOCAD_SRC, DEST_DIR)
  File "./gocad2collada.py", line 302, in process
    ok = self.process_others(whole_file_lines, dest_dir, file_name, base_xyz, filename_str, src_dir, ext_str, out_filename)
  File "./gocad2collada.py", line 198, in process_others
    if has_result:
UnboundLocalError: local variable 'has_result' referenced before assignment

edd@edd-VirtualBox:~/Documents/gitkraken/geomodel-2-3dweb/scripts$
```

config.json:
```json
{
    "ModelProperties": {
        "crs": "EPSG:27700",    
        "name": "Glasgow Bedrock", 
        "modelUrlPath": "glasgow", 
        "init_cam_dist": 0.0, 
        "proj4_defn": "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy+datum=OSGB36 +units=m +no_defs" 
    },
    "GroupStructure": {}
}

```

**Comment by KoalaGeo** [comment]
Found the issue, .ts files don't have projection/datum declared: 
```
}

GOCAD_ORIGINAL_COORDINATE_SYSTEM

NAME " Pdgm_Epic Local" 

PROJECTION Unknown

DATUM Unknown

AXIS_NAME X Y Z

AXIS_UNIT m m m

ZPOSITIVE Elevation

END_ORIGINAL_COORDINATE_SYSTEM

GEOLOGICAL_FEATURE Faults_Clipped

GEOLOGICAL_TYPE fault

PROPERTIES U V skua_model_stratigraphy_plus skua_model_stratigraphy_minus skua_model_stratigraphy_throw skua_model_Rockhead_t_plus skua_model_Rockhead_t_minus skua_model_Rockhead_t_throw skua_model_Topo_t_plus skua_model_Topo_t_minus skua_model_Topo_t_throw skua_model_TopMiddleCoalMeasuresFormation_t_plus skua_model_TopMiddleCoalMeasuresFormation_t_minus skua_model_TopMiddleCoalMeasuresFormation_t_throw

PROP_LEGAL_RANGES **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** **none**  **none** 

NO_DATA_VALUES -99999 -99999 -9999.990234375 -9999.990234375 -99999 -9999.990234375 -9999.990234375 -99999 -9999.990234375 -9999.990234375 -99999 -9999.990234375 -9999.990234375 -99999 

PROPERTY_CLASSES parametric_coordinate parametric_coordinate skua_model_stratigraphy skua_model_stratigraphy skua_model_stratigraphy_throw skua_model_rockhead_t skua_model_rockhead_t skua_model_rockhead_t_throw skua_model_topo_t skua_model_topo_t skua_model_topo_t_throw skua_model_topmiddlecoalmeasuresformation_t skua_model_topmiddlecoalmeasuresformation_t skua_model_topmiddlecoalmeasuresformation_t_throw

PROPERTY_KINDS " Real Number"  " Real Number"  " Real Number"  " Real Number"  Height " Real Number"  " Real Number"  Height " Real Number"  " Real Number"  Height " Real Number"  " Real Number"  Height

PROPERTY_SUBCLASSES QUANTITY Float QUANTITY Float QUANTITY Float QUANTITY Float LINEARFUNCTION Float 1  0  QUANTITY Float QUANTITY Float LINEARFUNCTION Float 1  0  QUANTITY Float QUANTITY Float LINEARFUNCTION Float 1  0  QUANTITY Float QUANTITY Float LINEARFUNCTION Float 1  0 

ESIZES 1  1  1  1  1  1  1  1  1  1  1  1  1  1 

UNITS unitless unitless unitless unitless m unitless unitless m unitless unitless m unitless unitless m

PROPERTY_CLASS_HEADER X {

kind: X

unit: m

pclip: 99

}
```

**Comment by KoalaGeo** [comment]
Updated to 
```
GOCAD_ORIGINAL_COORDINATE_SYSTEM
NAME "Glasgow Bedrock" 
PROJECTION " OSGB 1936 / British National Grid" 
DATUM " Mean Sea Level" 
AXIS_NAME X Y Z
AXIS_UNIT m m m
ZPOSITIVE Elevation
```

Still getting error. 
What is it expecting in the Name attribute? EPSG Code?

**Comment by KoalaGeo** [comment]
Tidied .ts and config.json so consistent, and using "name" from https://epsg.io/27700 

.ts file: 
```
GOCAD TSurf 1 
HEADER {
name: 02_Rockhead_50m_GGERFS_Predrill
*path*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
*solid*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
*atoms*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
*line*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
*derrick*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
*panel3d*color: 0.8243977201636881 0.13966658944264054 0.7399397962726653 1
use_feature_color: false
}
GOCAD_ORIGINAL_COORDINATE_SYSTEM
NAME " OSGB 1936 / British National Grid" 
PROJECTION " OSGB 1936 / British National Grid" 
DATUM " Mean Sea Level" 
AXIS_NAME X Y Z
AXIS_UNIT m m m
ZPOSITIVE Elevation
END_ORIGINAL_COORDINATE_SYSTEM
GEOLOGICAL_FEATURE Rockhead
GEOLOGICAL_TYPE topographic
PROPERTY_CLASS_HEADER X {
kind: X
unit: m
pclip: 99
}
```

config.json

```json
{
    "ModelProperties": {
        "crs": "EPSG:27700",    
        "name": "OSGB 1936 / British National Grid", 
        "modelUrlPath": "glasgow", 
        "init_cam_dist": 0.0, 
        "proj4_defn": "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy+datum=OSGB36 +units=m +no_defs" 
    },
    "GroupStructure": {}
}
```

Error:
```shell
edd@edd-VirtualBox:~/Documents/gitkraken/geomodel-2-3dweb/scripts$ ./gocad2collada.py -g ~/Documents/UKGEOS/test.ts config.json
2020-02-11 12:10:03,000 -- __main__ -- INFO - 
Processing /home/edd/Documents/UKGEOS/test.ts
2020-02-11 12:10:03,062 -- lib.imports.gocad.gocad_importer -- WARNING - SORRY - Does not support non-DEFAULT coordinates: 'OSGB_1936_/_BRITISH_NATIONAL_GRID'
2020-02-11 12:10:03,062 -- __main__ -- WARNING - WARNING - could not process /home/edd/Documents/UKGEOS/test.ts
Traceback (most recent call last):
  File "./gocad2collada.py", line 513, in <module>
    converter.process(GOCAD_SRC, DEST_DIR)
  File "./gocad2collada.py", line 302, in process
    ok = self.process_others(whole_file_lines, dest_dir, file_name, base_xyz, filename_str, src_dir, ext_str, out_filename)
  File "./gocad2collada.py", line 198, in process_others
    if has_result:
UnboundLocalError: local variable 'has_result' referenced before assignment
```

**Comment by vjf** [comment]
I think if you:
1)	Delete your ‘geomodel-2-3dweb’ directory and recreate it with ‘git clone’
2)	Use the ‘-x’ flag when you run 'gocad2collada.py'

Then this issue will go away.

**Comment by KoalaGeo** [comment]
That's got it, thanks!
