### ISSUE TITLE
Json config float error

### ISSUE THREAD

**Issue by RichardScottOZ** [AuScope/geomodel-2-3dweb#4]
```python
2022-02-16 13:08:02,011 -- converters.gocad2webasset -- DEBUG - src_dir=E:\3D_Map_of_North_Queensland_2009_3D_Data\inversions_grav_mag_voxets\inversions\SGrids\Cloncurry, out_filename=E:\3D_Map_of_North_Queensland_2009_3D_Data\inversions_grav_mag_voxets\inversions\SGrids\Cloncurry_inversions_unconst_den@@, prop_idx=1)
2022-02-16 13:08:03,405 -- converters.gocad2webasset -- DEBUG - process() returns True
{'properties': {'crs': 'EPSG:28354', 'extent': [-30000.0, 292000.0, 7281000.0, 7843000.0], 'name': 'Cloncurry', 'init_cam_dist': '0.0', 'proj4_defn': '+proj=utm +zone=54 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'}, 'type': 'GeologicalModel', 'version': 1.0, 'groups': defaultdict(<class 'list'>, {'3D Volume Cloncurry inversions unconst den@@': [{'model_url': 'Cloncurry_inversions_unconst_den@@.gz', 'type': '3DVolume', 'include': True, 'displayed': False, 'display_name': 'CLONCURRY_INVERSIONS', 'volumeData': {'dataType': 'FLOAT_32', 'dataDims': (161, 281, 37), 'origin': (-30000.0, 7281000.0, -25000.0), 'size': [322000.0, 562000.0, 28000.0], 'maxVal': 2.960391044616699, 'minVal': 2.59062, 'rotation': [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]}, 'alt_group_label': '3D Volume Cloncurry inversions unconst den@@'}], '3D Volume Cloncurry inversions unconst sus@@': [{'model_url': 'Cloncurry_inversions_unconst_sus@@.gz', 'type': '3DVolume', 'include': True, 'displayed': False, 'display_name': 'CLONCURRY_INVERSIONS', 'volumeData': {'dataType': 'FLOAT_32', 'dataDims': (161, 281, 37), 'origin': (-30000.0, 7281000.0, -25000.0), 'size': [322000.0, 562000.0, 28000.0], 'maxVal': 0.18609100580215454, 'minVal': 0.0, 'rotation': [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]}, 'alt_group_label': '3D Volume Cloncurry inversions unconst sus@@'}]})}
Traceback (most recent call last):
  File "conv_webasset.py", line 270, in <module>
    converter.config_build_obj.create_json_config(ARGS.output_config, DEST_DIR, converter.params)
  File "C:\Users\rscott\OneDrive - OZ Minerals\Exploration2022\geomodel-2-3dweb\scripts\lib\config_builder.py", line 154, in create_json_config
    json.dump(config_dict, file_p, indent=4, sort_keys=True)
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\rscott\miniconda3\envs\pyvistabackground\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type float32 is not JSON serializable
```

```json
{'properties': {'crs': 'EPSG:28354', 'extent': [-30000.0, 292000.0, 7281000.0, 7843000.0], 'name': 'Cloncurry', 'init_cam_dist': '0.0', 'proj4_defn': '+proj=utm +zone=54 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'}, 'type': 'GeologicalModel', 'version': 1.0, 'groups': defaultdict(<class 'list'>, {'3D Volume Cloncurry inversions unconst den@@': [{'model_url': 'Cloncurry_inversions_unconst_den@@.gz', 'type': '3DVolume', 'include': True, 'displayed': False, 'display_name': 'CLONCURRY_INVERSIONS', 'volumeData': {'dataType': 'FLOAT_32', 'dataDims': (161, 281, 37), 'origin': (-30000.0, 7281000.0, -25000.0), 'size': [322000.0, 562000.0, 28000.0], 'maxVal': 2.960391044616699, 'minVal': 2.59062, 'rotation': [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]}, 'alt_group_label': '3D Volume Cloncurry inversions unconst den@@'}], '3D Volume Cloncurry inversions unconst sus@@': [{'model_url': 'Cloncurry_inversions_unconst_sus@@.gz', 'type': '3DVolume', 'include': True, 'displayed': False, 'display_name': 'CLONCURRY_INVERSIONS', 'volumeData': {'dataType': 'FLOAT_32', 'dataDims': (161, 281, 37), 'origin': (-30000.0, 7281000.0, -25000.0), 'size': [322000.0, 562000.0, 28000.0], 'maxVal': 0.18609100580215454, 'minVal': 0.0, 'rotation': [(1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)]}, 'alt_group_label': '3D Volume Cloncurry inversions unconst sus@@'}]})}
```

Not sure if on my end, first config file I made ,anyway. Data output would be similar though as far as datatypes between sgrids?

**Comment by vjf** [comment]
Hi Richard, please include the relevant files so I can reproduce and fix the error.

**Comment by RichardScottOZ** [comment]
Ok, 3D Map of North Queensland Data package is here.
https://ecat.ga.gov.au/geonetwork/srv/eng/catalog.search?node=srv#/metadata/69862

**Comment by vjf** [comment]
Fixed.
